import MySQL_connect as db;
# here cursor is "cursor"
db.cursor.execute('''CREATE TABLE IF NOT EXISTS BOOKS(
               BOOKID INT AUTO_INCREMENT PRIMARY KEY,
               BOOKTITLE VARCHAR(100) NOT NULL,
               AUTHORNAME VARCHAR(100) NOT NULL,
               STATUS VARCHAR(20) DEFAULT 'AVAILABLE',
                ADDEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UPDATEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
               )''')
db.cursor.execute('''CREATE TABLE IF NOT EXISTS USERS(
               USERID INT AUTO_INCREMENT PRIMARY KEY,
               FULLNAME VARCHAR(200) NOT NULL,
               EMAIL VARCHAR(100) NOT NULL UNIQUE,
               PHONE VARCHAR(15) NOT NULL UNIQUE,
               ROLE VARCHAR(50) NOT NULL,
               SALARY DECIMAL(10,2) DEFAULT 0.00,
               JOINEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UPDATEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
                )
               ''')
db.cursor.execute('''CREATE TABLE IF NOT EXISTS ISSUERS(
               ISSUERID INT AUTO_INCREMENT PRIMARY KEY,
               FULLNAME VARCHAR(200) NOT NULL,
               EMAIL VARCHAR(100) NOT NULL UNIQUE,
               PHONE VARCHAR(15) NOT NULL UNIQUE,
               ADDEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UPDATEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
                )''')
db.cursor.execute('''CREATE TABLE IF NOT EXISTS TRANSACTIONS(
               TRANSACTIONID INT AUTO_INCREMENT PRIMARY KEY,
               BOOKID INT NOT NULL,
               ISSUEDTOID INT NOT NULL,
               ISSUEDBYID INT NOT NULL,
               ISSUEDON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
               RETURNEDON TIMESTAMP NULL,
               STATUS VARCHAR(20) DEFAULT 'ISSUED',
               FINE DECIMAL(10,2) DEFAULT 0.00,
               FOREIGN KEY (BOOKID) REFERENCES BOOKS(BOOKID),
               FOREIGN KEY (ISSUEDTOID) REFERENCES USERS(USERID),
               FOREIGN KEY (ISSUEDBYID) REFERENCES ISSUERS(ISSUERID)
               )''')#status will be either ISSUED or RETURNED or Failed
db.conn.commit()
